[package]
name = "rustboy"
version = "0.1.0"
authors = ["Chase Miller"]

[dependencies]
bitflags = "1"
byteorder = "1"
clap = "2.33.3"
enum_primitive = "*"
fnv = "1"
lazy_static = "1.4.0"
minifb = "0.13.0"